name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel all jobs if one fails
      matrix:
        ruby-version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        postgres-version: ["10", "11", "12", "13", "14", "15", "16"]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: pg_hash_func_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          health-cmd pg_isready
          --host=localhost
          --port=5432
          --dbname=pg_hash_func_test
          --username=postgres
          health-interval 10s
          health-timeout 5s
          health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        env:
          PGHOST: localhost
          PGPORT: 5432 # Port specified in services
          PGDATABASE: pg_hash_func_test # DB name specified in services env
          PGUSER: postgres # User specified in services env
          PGPASSWORD: password # Password specified in services env
          RAILS_ENV: test
          RACK_ENV: test
        run: bundle exec rspec
